### ISSUE TITLE
后面不会再开发了吗?

### ISSUE THREAD

**Issue by yebei199** [TThz-hz/NeteaseCloudMusic#1]
好多功能都没有, 比如设置, 换肤这些

**Comment by tthzwq** [comment]
这个是之前打发时间写着玩的，以后应该不会再开发了，太忙了，不好意思啊。

**Comment by yebei199** [comment]
> 这个是之前打发时间写着玩的，以后应该不会再开发了，太忙了，不好意思啊。

好吧, 感觉目前还没有tauri的网易云播可用win的放器, 找到的都是electron的
